name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # rebuild any time you push to main

# Pages needs these token scopes
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages" # one deploy at a time
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4 # Node 20 by default :contentReference[oaicite:1]{index=1}
        with:
          cache: npm

      - run: npm ci
      - run: npm run build # creates dist/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3 # bundles ./dist → “github-pages” artifact :contentReference[oaicite:2]{index=2}
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # publishes the artifact :contentReference[oaicite:3]{index=3}
